- name: Ensure apt keys
  become: yes
  apt_key:
    id: "14219A96E15E78F4"
    url: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
    state: present

- name: Ensure apt repositories
  become: yes
  apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ bionic main"
    - "deb-src https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ bionic main"

- name: Install gitlab
  become: yes
  apt:
    name: "{{ packages }}"
  environment:
    EXTERNAL_URL: "http://gitlab.simon816.com"
  vars:
    packages:
      - gitlab-ce

- name: Configure gitlab
  become: yes
  blockinfile:
    path: /etc/gitlab/gitlab.rb
    block: |
        external_url 'https://gitlab.simon816.com'
        letsencrypt['enable'] = false
        # Disable the built-in Postgres
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_database'] = '{{ db.gitlab.name }}'
        gitlab_rails['db_host'] = '{{ db.gitlab.host }}'
        gitlab_rails['db_port'] = {{ db.gitlab.port }}
        gitlab_rails['db_username'] = '{{ db.gitlab.user }}'
        gitlab_rails['db_password'] = '{{ db.gitlab.pass }}'
  notify:
    - reconfigure gitlab

- name: Ensure gitlab SSL directory
  become: yes
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Ensure gitlab SSL public cert
  become: yes
  copy:
    src: certs/simon816.com.pem
    dest: /etc/gitlab/ssl/gitlab.simon816.com.crt
  notify:
    - reload gitlab nginx

- name: Ensure gitlab SSL private cert
  become: yes
  copy:
    src: certs/simon816.com.key
    dest: /etc/gitlab/ssl/gitlab.simon816.com.key
  notify:
    - reload gitlab nginx
