#!/usr/bin/env python3

from collections import defaultdict
import sys
import os
import pickle
import zlib
from hashlib import md5

import doveadm
from envelope_reader import EnvelopeReader

IGNORE_LOCAL = ('INBOX', 'Junk', 'Sent')
IGNORE_REMOTE = (*IGNORE_LOCAL, 'Posteo', 'Gateway', 'Personal')
IGNORE_FLAGS = set(('\\Recent',))
BATCH_SIZE = 1000
CACHE_PATH = '/etc/dovecot/sync/env_cache'

"""
Future enhancements:
Skip if mailbox unchanged since last run
Maybe trigger when mailbox changed rather than cron
"""

class ChangeSet:

    def __init__(self):
        self.mail_actions = defaultdict(list)

    def set_flags(self, key, flags, mailbox, uid):
        self.mail_actions[key].append(('flags', flags, mailbox, uid))

    def add_delete(self, key, mailbox, uid):
        self.mail_actions[key].append(('delete', mailbox, uid))

    def add_copy(self, key, src_mailbox, src_uid, dest_mailbox):
        self.mail_actions[key].append(('copy', src_mailbox, src_uid, dest_mailbox))

    def apply(self):
        move_targets = defaultdict(lambda: defaultdict(list))
        flag_targets = defaultdict(lambda: defaultdict(list))
        copy_targets = defaultdict(lambda: defaultdict(list))
        delete_targets = defaultdict(list)
        for k, actions in self.mail_actions.items():
            actions = self.rewrite_move(actions)
            for (atype, *args) in actions:
                if atype == 'flags':
                    flags, mailbox, uid = args
                    flag_targets[flags][mailbox].append(uid)
                elif atype == 'delete':
                    mailbox, uid = args
                    delete_targets[mailbox].append(uid)
                elif atype == 'copy':
                    src_mb, src_uid, dest_mb = args
                    copy_targets[dest_mb][src_mb].append(src_uid)
                elif atype == 'move':
                    src_mb, src_uid, dest_mb = args
                    move_targets[dest_mb][src_mb].append(src_uid)

        for flags, searchdict in flag_targets.items():
            for search in chunked_search(searchdict):
                doveadm.set_flags(' '.join(flags), search)

        for dest_mb, searchdict in copy_targets.items():
            for search in chunked_search(searchdict):
                doveadm.copy(dest_mb, search)

        for dest_mb, searchdict in move_targets.items():
            for search in chunked_search(searchdict):
                doveadm.move(dest_mb, search)

        if delete_targets:
            for search in chunked_search(delete_targets):
                doveadm.delete(search)

    def rewrite_move(self, actions):
        sources = [a[1:] for a in actions if a[0] == 'delete']
        if not sources:
            return actions
        copies = [a[1:] for a in actions if a[0] == 'copy']
        if not copies:
            return actions

        source = sources.pop(0)
        first_copy = copies.pop(0)

        # keep unrelated actions
        new_actions = [a for a in actions if a[0] not in ('delete', 'copy')]
        # If we have more than one copy, do those with the remove src first
        for cp in copies:
            new_actions.append(('copy', source[0], source[1], cp[2]))
        # transform the first copy into a move
        new_actions.append(('move', source[0], source[1], first_copy[2]))
        # If we have more than one delete, do the rest too
        for d in sources:
            new_actions.append(('delete', *d))
        return new_actions

def create_mb_search(mailbox, uidlist):
    search = ['mailbox', mailbox]
    search.extend(doveadm.search_or(*(['uid', uid] for uid in uidlist)))
    return search

def chunked_search(searchdict):
    for mailbox, uidlist in searchdict.items():
        for i in range(0,  len(uidlist), BATCH_SIZE):
            search = create_mb_search(mailbox, uidlist[i:i + BATCH_SIZE])
            yield search

def key(env):
    return (env.message_id, env.date)

def cached_key(c, r, env_data):
    uniq_key, cache_key = c.get(env_data)
    if uniq_key is None:
        env = r.read_envelope(env_data)
        uniq_key = key(env)
        c[cache_key] = uniq_key
    return uniq_key

def flag_set(flags):
    if not flags:
        return frozenset()
    return frozenset(set(flags.decode('utf8').split(' ')) - IGNORE_FLAGS)

class EnvelopeCache:

    def __init__(self):
        self.layer1 = {}

    def get(self, env):
        h1 = zlib.adler32(env)
        h2 = md5(env).digest()
        if h1 in self.layer1:
            return self.layer1[h1].get(h2), (h1, h2)
        return None, (h1, h2)

    def __setitem__(self, key, val):
        h1, h2 = key
        if h1 not in self.layer1:
            self.layer1[h1] = {}
        self.layer1[h1][h2] = val

def sync_mailbox(r, changeset, mailbox, remote_boxes):
    if mailbox in IGNORE_LOCAL:
        return

    print("Doing", mailbox)
    local = {}

    remote_mailbox = 'Posteo.' + mailbox
    if remote_mailbox not in remote_boxes:
        doveadm.create_mailbox(remote_mailbox)
    else:
        remote_boxes.remove(remote_mailbox)

    for mail in doveadm.fetch('uid imap.envelope flags', ['mailbox', mailbox, 'not', 'deleted']):
        local[cached_key(c, r, mail['imap.envelope'])] = { 'uid': mail['uid'], 'flags': flag_set(mail['flags']) }

    for mail in doveadm.fetch('uid imap.envelope flags', ['mailbox', remote_mailbox, 'all']):
        k = cached_key(c, r, mail['imap.envelope'])
        if k in local:
            l_mail = local[k]
            if l_mail['flags'] != flag_set(mail['flags']):
                changeset.set_flags(k, l_mail['flags'], remote_mailbox, mail['uid'])
            del local[k]
        else:
            # Delete from remote
            changeset.add_delete(k, remote_mailbox, mail['uid'])

    # Copy local -> remote
    for k, mail in local.items():
        changeset.add_copy(k, mailbox, mail['uid'], remote_mailbox)

def sync_inbox(r):
    mails = doveadm.fetch('uid imap.envelope', ['mailbox', 'Posteo.INBOX', 'all'])

    delete_list = []
    move_list = []
    for mail in mails:
        uid = mail['uid']
        env = r.read_envelope(mail['imap.envelope'])
        # TODO possibly SENTON
        print("[%s]" % uid.decode('utf8'), "Message", env.message_id)
        search = doveadm.search(['header', 'Message-ID', env.message_id])
        if len(list(search)):
            # If we have the email, delete from remote
            print("Already got, deleting remote")
            delete_list.append(uid)
        else:
            # Otherwise, we move it from remote to local
            print("Missing, importing from remote")
            # Possibly use import instead:
            # sudo doveadm import -u simon maildir:~/Maildir "Posteo" mailbox "simon816"
            move_list.append(uid)

    if len(delete_list):
        search = ['mailbox', 'Posteo.INBOX']
        search.extend(doveadm.search_or(*(['uid', uid] for uid in delete_list)))
        doveadm.delete(search)

    if len(move_list):
        search = ['mailbox', 'Posteo.INBOX']
        search.extend(doveadm.search_or(*(['uid', uid] for uid in move_list)))
        doveadm.move('INBOX', search)

    # Look for mails we imported because they were missing, that later became duplicates
    mails = doveadm.fetch('uid imap.envelope', ['mailbox', 'INBOX', 'header', 'Delivered-To', 'simon816@posteo.net'])
    delete_list = []

    for mail in mails:
        uid = mail['uid']
        env = r.read_envelope(mail['imap.envelope'])
        search = doveadm.search(['header', 'Message-ID', env.message_id, 'not', 'mailbox', 'INBOX'])
        if len(list(search)):
            print("[%s] %s already exists, removing from inbox" % (uid, env.message_id))
            # Another email exists this this message ID, delete from local
            delete_list.append(uid)

    if len(delete_list):
        search = ['mailbox', 'INBOX']
        search.extend(doveadm.search_or(*(['uid', uid] for uid in delete_list)))
        doveadm.delete(search)

def get_remote_boxes():
    # Use status since mailbox list also returns intermediate namespaces
    mboxes = doveadm.status('uidnext', 'Posteo.*')
    return set(mboxes.keys()) - set('Posteo.' + mb for mb in IGNORE_REMOTE)

def sync_non_inbox(r, changeset):
    remote_boxes = get_remote_boxes()

    for mailbox in doveadm.get_mailboxes():
        sync_mailbox(r, changeset, mailbox, remote_boxes)

    changeset.apply()

    if remote_boxes:
        doveadm.delete_mailbox(*remote_boxes)


if __name__ == '__main__':
    if os.path.exists(CACHE_PATH):
        try:
            with open(CACHE_PATH, 'rb') as f:
                c = pickle.load(f)
        except:
            c = EnvelopeCache()
    else:
        c = EnvelopeCache()
    r = EnvelopeReader()
    changeset = ChangeSet()
    if len(sys.argv) > 1:
        for mailbox in sys.argv[1:]:
            if mailbox == 'INBOX':
                sync_inbox(r)
            else:
                sync_mailbox(r, changeset, mailbox, get_remote_boxes())
        changeset.apply()
    else:
        sync_inbox(r)
        sync_non_inbox(r, changeset)

    with open(CACHE_PATH, 'wb') as f:
        pickle.dump(c, f)
