- name: postalias
  become: yes
  command: postalias /etc/aliases

- name: reload postfix
  become: yes
  service:
    name: postfix
    state: reloaded

- name: reload dovecot
  become: yes
  service:
    name: dovecot
    state: reloaded

- name: restart opendkim
  become: yes
  service:
    name: opendkim
    state: restarted
