- name: Ensure apt keys
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0x39BD841E4BE5FB195A65400E6A26B1AE64C3C388"

- name: Ensure apt repositories
  become: yes
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse"

- name: Install libssl1.1
  become: yes
  apt:
    update_cache: yes
    deb: "http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb"

- name: Install DB packages
  become: yes
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - mongodb-org-server
    - mongodb-database-tools
    - mongodb-mongosh
    - python3-pip

- name: Install pymongo
  become: yes
  pip:
    name: pymongo>=3.12

- name: Ensure mongodb directory
  become: yes
  file:
    path: /srv/mongodb
    owner: mongodb
    group: mongodb
    state: directory

- name: Get mongodb data dir
  stat:
    path: /var/lib/mongodb
  register: mongodb_data

- name: Stop mongod if first run
  become: yes
  service:
    name: mongod
    state: stopped
  when: not mongodb_data.stat.islnk

- name: Remove default mongodb data
  become: yes
  file:
    path: /var/lib/mongodb
    state: absent
  when: not mongodb_data.stat.islnk

- name: Link mongodb data
  become: yes
  file:
    src: /srv/mongodb
    dest: /var/lib/mongodb
    force: yes
    state: link
    owner: mongodb
    group: mongodb

- name: Ensure mongod started
  become: yes
  service:
    name: mongod
    state: started

- name: Configure mongodb IP
  become: yes
  lineinfile:
    path: /etc/mongod.conf
    regexp: '  bindIp: .+'
    line: "  bindIp: '0.0.0.0'"
  notify:
    - restart mongod

- name: Configure mongodb
  become: yes
  blockinfile:
    path: /etc/mongod.conf
    block: |
      security:
        authorization: enabled
  notify:
    - restart mongod

- name: Ensure mongodb root user
  mongodb_user:
    database: admin
    name: root
    password: root
    roles: root
  register: mongo_root_check
