- name: Install apache
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - apache2

- name: Enable apache modules for common headers
  become: yes
  apache2_module:
    state: present
    name: "{{ item }}"
  loop:
    - headers
    - ssl
  notify:
    - restart apache

- name: Restart apache now
  meta: flush_handlers

- import_tasks: ssl.yml

- name: Configure apache common headers
  become: yes
  copy:
    src: common-headers.conf
    dest: /etc/apache2/conf-available/common-headers.conf
  notify:
    - restart apache

- name: Enable apache common headers
  become: yes
  command: a2enconf common-headers
  args:
    creates: /etc/apache2/conf-enabled/common-headers.conf
  notify:
    - restart apache

- name: Ensure apache is running
  become: yes
  service:
    name: apache2
    state: started

