- name: Ensure SSL public cert
  become: yes
  copy:
    src: certs/simon816.com.pem
    dest: /etc/ssl/certs/ssl-cert-simon816.pem
  notify:
    - restart apache

- name: Ensure SSL private cert
  become: yes
  copy:
    src: certs/simon816.com.key
    dest: /etc/ssl/private/ssl-cert-simon816.key
  notify:
    - restart apache

- name: Configure apache SSL
  become: yes
  copy:
    src: simon816-ssl.conf
    dest: /etc/apache2/conf-available/simon816-ssl.conf
  notify:
    - restart apache

- name: Apache SSL common
  become: yes
  copy:
    src: ssl-common.conf
    dest: /etc/apache2/conf-available/ssl-common.conf
  notify:
    - restart apache

- name: Enable apache common SSL
  become: yes
  command: a2enconf ssl-common
  args:
    creates: /etc/apache2/conf-enabled/ssl-common.conf
  notify:
    - restart apache

- name: Apache dhparams
  become: yes
  openssl_dhparam:
    path: /etc/ssl/apache-dhparams.pem
    size: 2048
  notify:
    - restart apache

- name: Apache default SSL virtualhost
  become: yes
  copy:
    src: default-ssl.conf
    dest: /etc/apache2/sites-available/10-simon816-ssl.conf
  notify:
    - restart apache

# For some reason this causes rss-bridge to not work
- name: Disable default SSL virtualhost
  become: yes
  command: a2dissite 10-simon816-ssl
  args:
    removes: /etc/apache2/sites-enabled/10-simon816-ssl.conf
  notify:
    - restart apache


