---
- hosts: cloud

  pre_tasks:
  - name: Expand disk
    become: yes
    command: growpart /dev/disk/by-path/pci-0000:00:07.0 1
    register: growpart
    changed_when: "'CHANGED' in growpart.stdout"
    failed_when: "growpart.rc != 0 and 'NOCHANGE' not in growpart.stdout"

  - name: Expand filesystem if needed
    become: yes
    filesystem:
      dev: /dev/disk/by-path/pci-0000:00:07.0-part1
      fstype: ext4
      resizefs: yes

  - name: Early networking
    import_role:
      name: intnet-node

  - name: Install NFS
    become: yes
    apt:
      update_cache: yes
      name: nfs-common

  - name: Set hostname
    become: yes
    hostname:
      name: cloud.simon816.com

  # sudo tries to DNS query own hostname, return localhost
  - name: Own hostname is localhost
    become: yes
    lineinfile:
      path: /etc/hosts
      line: "127.0.0.1 localhost cloud.simon816.com"
      search_string: "127.0.0.1"

  tasks:
  - name: hosts file self mapping
    become: yes
    lineinfile:
      path: /etc/hosts
      line: "{{ inventory_hostname }} {{ item }}"
      search_string: "{{ item }}"
    loop:
      - rss-bridge.simon816.com
      - ical-bridge.simon816.com
      - nextcloud.simon816.com

  roles:
    - mail-forwarder
    - naemon-remote
    - auto-updates
    - apache
    - nextcloud
    - xbrowsersync
    - wekan
    - ttrss
    - rss-bridge
    - role: backup-spool
      vars:
        backup_paths:
          ttrss_icons: /var/www/ttrss/cache/feed-icons/
        backup_scripts:
          nextcloud: |
            sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --on
            perform_backup /var/www/nextcloud/
            sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --off
        restore_scripts:
          nextcloud: |
            sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --on
            restore_path "nextcloud/config" "/var/www/nextcloud/config/"
            sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --off
          nextcloud_all: |
            sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --on
            restore_path "nextcloud" "/var/www/nextcloud/"
            sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --off
