---
- hosts: cloud

  tasks:
  - name: Install NFS
    become: yes
    apt:
      name: nfs-common

  roles:
    - intnet-node
    - apache
    - nextcloud
    - xbrowsersync
    - wekan
    - pleroma
