---
- hosts: cloud

  tasks:
  - name: Install NFS
    become: yes
    apt:
      name: nfs-common

  roles:
    - intnet-node
    - apache
    - nextcloud
#    - xbrowsersync
    - wekan
    - pleroma
    - ttrss
    - role: backup-spool
      vars:
        backup_paths:
          pleroma_config: /var/www/pleroma/config/
          pleroma_uploads: /var/www/pleroma/uploads/
        backup_scripts:
          nextcloud: |
            sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --on
            perform_backup /var/www/nextcloud/
            sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --off
