---
- hosts: cloud

  pre_tasks:
  - name: Expand disk
    become: yes
    command: growpart /dev/disk/by-path/pci-0000:00:07.0 1
    register: growpart
    changed_when: "'CHANGED' in growpart.stdout"
    failed_when: "growpart.rc != 0 and 'NOCHANGE' not in growpart.stdout"

  - name: Install NFS
    become: yes
    apt:
      update_cache: yes
      name: nfs-common

  roles:
    - intnet-node
    - apache
    - nextcloud
    - xbrowsersync
    - wekan
    #- pleroma
    - ttrss
    - role: backup-spool
      vars:
        backup_paths:
          pleroma_config: /var/www/pleroma/config/
          pleroma_uploads: /var/www/pleroma/uploads/
        backup_scripts:
          nextcloud: |
            sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --on
            perform_backup /var/www/nextcloud/
            sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --off
