---
- hosts: controller

  pre_tasks:
    - name: Configure intnet netplan
      become: yes
      copy:
        src: net/controller-intnet.yaml
        dest: /etc/netplan/10-intnet.yaml
      notify:
        - apply netplan

    - name: Clear bootstrap network
      become: yes
      file:
        state: absent
        path: /etc/netplan/50-cloud-init.yaml
      notify:
        - apply netplan

    - name: Ensure ansible log directory
      become: yes
      file:
        path: /var/log/ansible
        state: directory
        owner: ansible
        group: ansible

    - name: Set hostname
      become: yes
      hostname:
        name: controller.simon816.com

    - name: Apply handlers
      meta: flush_handlers

  handlers:
    - name: apply netplan
      become: yes
      command: netplan apply

  roles:
    - mail-forwarder
#    - intnet-node
