---
- hosts: dev

  pre_tasks:
  - name: git user
    become: yes
    user:
      name: git
      password_lock: yes

  - name: Set hostname
    become: yes
    hostname:
      name: dev.simon816.com

  roles:
    - intnet-node
    - mail-forwarder
    - naemon-remote
    - auto-updates
    - gitea
    - role: nginx
      vars:
        site: dev
