---
- hosts: dev

  pre_tasks:
  - name: git user
    become: yes
    user:
      name: git
      password_lock: yes

  roles:
    - intnet-node
    - gitea
    - role: nginx
      vars:
        site: dev
