---
- hosts: dev

  pre_tasks:
  - name: git user
    become: yes
    user:
      name: git
      password_lock: yes

  - name: Set hostname
    become: yes
    hostname:
      name: dev.simon816.com

  # sudo tries to DNS query own hostname, return localhost
  - name: Own hostname is localhost
    become: yes
    lineinfile:
      path: /etc/hosts
      line: "127.0.0.1 localhost dev.simon816.com"
      search_string: "127.0.0.1"

  roles:
    - intnet-node
    - mail-forwarder
    - naemon-remote
    - auto-updates
    - gitea
    - role: nginx
      vars:
        site: dev
