---
- hosts: gateway

  pre_tasks:

  - name: Set hostname
    become: yes
    hostname:
      name: gateway.simon816.com

  # sudo tries to DNS query own hostname, return localhost
  - name: Own hostname is localhost
    become: yes
    lineinfile:
      path: /etc/hosts
      line: "127.0.0.1 localhost gateway.simon816.com"
      search_string: "127.0.0.1"

  roles:
    - gateway
    - bind9
    - mail-forwarder
    - naemon-remote
    - auto-updates
