---
- hosts: mail
  pre_tasks:
  - name: Ensure data disk configured
    become: yes
    parted:
      device: /dev/disk/by-path/pci-0000:00:09.0
      number: 1
      state: present

  - name: Ensure data disk filesystem
    become: yes
    filesystem:
      dev: /dev/disk/by-path/pci-0000:00:09.0-part1
      fstype: ext4

  - name: Mount data disk
    become: yes
    mount:
      fstype: ext4
      src: /dev/disk/by-path/pci-0000:00:09.0-part1
      path: /home
      state: mounted

  roles:
    - intnet-node
    - mail-server
    - role: backup-spool
      vars:
        backup_scripts:
          dovecot: |
            # need to set permissions for dovecot
            sudo chmod 777 /var/spool/backup
            sudo doveadm backup -u simon maildir:/var/spool/backup/dovecot-simon/
            sudo chmod 700 /var/spool/backup
