---
- hosts: sinkhole

  pre_tasks:
  - name: Expand disk
    become: yes
    command: growpart /dev/disk/by-path/pci-0000:00:07.0 1
    register: growpart
    changed_when: "'CHANGED' in growpart.stdout"
    failed_when: "growpart.rc != 0 and 'NOCHANGE' not in growpart.stdout"

  - name: Expand filesystem if needed
    become: yes
    filesystem:
      dev: /dev/disk/by-path/pci-0000:00:07.0-part1
      fstype: ext4
      resizefs: yes

  - name: Ensure tmp disk configured
    become: yes
    parted:
      device: /dev/disk/by-path/pci-0000:02:00.0
      number: 1
      state: present

  - name: Ensure tmp disk filesystem
    become: yes
    filesystem:
      dev: /dev/disk/by-path/pci-0000:02:00.0-part1
      fstype: ext4

  - name: Mount tmp disk
    become: yes
    mount:
      fstype: ext4
      src: /dev/disk/by-path/pci-0000:02:00.0-part1
      path: /tmp
      state: mounted

  - name: sinkhole user
    become: yes
    user:
      name: sinkhole
      password_lock: yes
      shell: /sbin/nologin

  - name: Early networking
    import_role:
      name: intnet-node

  - name: Install NFS
    become: yes
    apt:
      update_cache: yes
      name: nfs-common

  - name: Mount sinkhole NFS
    become: yes
    mount:
      fstype: nfs
      src: "10.80.0.1:/media/bd/sinkhole"
      path: /srv
      state: mounted

  - name: Ensure sinkhole LFS mount point
    become: yes
    file:
      path: /media/lfs
      state: directory
      owner: sinkhole
      group: sinkhole

  - name: Mount sinkhole NFS large file store
    become: yes
    mount:
      fstype: nfs
      src: "10.80.0.1:/media/md/sinkhole"
      path: /media/lfs
      state: mounted

  roles:
    - naemon-remote
    - auto-updates
    - sonarr
    - radarr
    - jackett
    - deluge
    - role: nginx
      vars:
        site: sinkhole
    - youtube-fetcher
    - role: backup-spool
      vars:
        backup_paths:
          sonarr: /home/sinkhole/.config/Sonarr/
          deluge: /var/lib/deluged/config/
          radarr: /home/sinkhole/.config/Radarr/
