---
- hosts: sinkhole

  pre_tasks:
  - name: Expand disk
    become: yes
    command: growpart /dev/disk/by-path/pci-0000:00:07.0 1
    register: growpart
    changed_when: "'CHANGED' in growpart.stdout"
    failed_when: "growpart.rc != 0 and 'NOCHANGE' not in growpart.stdout"

  - name: Expand filesystem if needed
    become: yes
    filesystem:
      dev: /dev/disk/by-path/pci-0000:00:07.0-part1
      fstype: ext4
      resizefs: yes

  - name: sinkhole user
    become: yes
    user:
      name: sinkhole
      password_lock: yes
      shell: /sbin/nologin

  - name: Install NFS
    become: yes
    apt:
      update_cache: yes
      name: nfs-common

  - name: Mount sinkhole NFS
    become: yes
    mount:
      fstype: nfs
      src: "10.80.0.1:/media/bd/sinkhole"
      path: /srv
      state: mounted

  roles:
    - intnet-node
    - sonarr
    - radarr
    - jackett
    - deluge
    #- sabnzbplus
    - nginx
    - role: backup-spool
      vars:
        backup_paths:
          sonarr: /home/sinkhole/.config/Sonarr/
          deluge: /var/lib/deluged/config/
          radarr: /home/sinkhole/.config/Radarr/
