---
- hosts: hypervisor
  remote_user: simon
  tasks:
  - name: Define intnet
    virt_net:
      command: define
      name: intnet
      xml: '{{ lookup("file", "net/intnet.xml") }}'

  - name: Ensure intnet active
    virt_net:
      name: intnet
      state: active

  - name: Autostart intnet
    virt_net:
      name: intnet
      autostart: yes

  - name: Provision machines
    virt:
      command: define
      xml: '{{ lookup("template", "vm/" + item + ".xml.j2") }}'
    loop:
      - controller
      - gateway
      - dbserver
      - cloud
      - sinkhole
     # - mail

  - name: Ensure machines are running
    virt:
      name: "{{ item }}"
      state: running
    loop:
      - gateway
      - dbserver
      - cloud
      - sinkhole2
     # - mail
