- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - postfix
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-sieve
    - opendkim
    - opendkim-tools
    - python3-pip

- name: Install sync dependencies
  become: yes
  pip:
    name: imapclient

- name: Copy postfix configuration
  become: yes
  copy:
    src: postfix-etc/
    dest: /etc/postfix/
  notify:
    - reload postfix

- name: Copy postfix posteo auth
  become: yes
  template:
    src: postfix/password.j2
    dest: /etc/postfix/password
    owner: root
    group: root
    mode: 0600
  vars:
    posteo_password: "{{ lookup('unvault', 'posteo_password') }}"

- name: postfix mailname
  become: yes
  copy:
    content: "mail.simon816.com\n"
    dest: /etc/mailname
  notify:
    - reload postfix

- name: postmap
  include_tasks: postmap.yml
  loop:
    - header_checks
    - sender_map
    - sender_map_machines
    - sender_canonical
    - password
    - virtual
  loop_control:
    loop_var: dbfile

- name: aliases file
  become: yes
  copy:
    src: postfix/aliases
    dest: /etc/aliases
  notify:
    - postalias

- name: Ensure mail cert directory
  become: yes
  file:
    path: /etc/ssl/mail
    state: directory

- name: Copy gateway client cert
  become: yes
  copy:
    src: postfix/mxgateway.simon816.com.cert.pem
    dest: /etc/ssl/mail/mxgateway.simon816.com.cert.pem
  notify:
    - reload postfix

- name: Copy dovecot configuration
  become: yes
  copy:
    src: "{{ item }}"
    dest: /etc/dovecot/conf.d/
  with_fileglob:
    - "dovecot/*.conf"
    - "dovecot/*.conf.ext"
  notify:
    - reload dovecot

- name: Copy posteo password
  become: yes
  copy:
    src: posteo_password
    dest: /etc/dovecot/posteo_password
    owner: root
    group: root
    mode: 0600
  notify:
    - reload dovecot

- name: Copy dovecot users
  become: yes
  copy:
    src: dovecot/users
    dest: /etc/dovecot/users
  notify:
    - reload dovecot

- name: Copy dovecot auth
  become: yes
  copy:
    src: dovecot/passwd
    dest: /etc/dovecot/passwd
    owner: dovecot
    group: dovecot
    mode: 0600
  notify:
    - reload dovecot

- name: Standard sieve directory
  become: yes
  become_user: simon
  file:
    path: /home/simon/sieve
    state: directory
    mode: 0700

- name: stat main.sieve
  become: yes
  become_user: simon
  stat:
    path: /home/simon/sieve/main.sieve
  register: sieve_stat

- name: Standard sieve file
  become: yes
  become_user: simon
  file:
    path: /home/simon/sieve/main.sieve
    mode: 0600
    state: touch
  when: not sieve_stat.stat.exists

- name: Standard sieve layout
  become: yes
  become_user: simon
  file:
    src: /home/simon/sieve/main.sieve
    dest: /home/simon/.dovecot.sieve
    state: link

- name: Copy dovecot sync code
  become: yes
  copy:
    src: sync
    dest: /etc/dovecot/
    mode: preserve

- name: dovecot sync cron
  become: yes
  cron:
    name: dovecot sync
    minute: "0,30"
    job: "/etc/dovecot/sync/sync-mailboxes 2>&1 | logger -t sync-mailboxes"

- name: Utility scripts
  copy:
    src: utils/
    dest: /home/ansible/
    mode: 0775

- name: Postfix in DKIM group
  become: yes
  user:
    append: yes
    name: postfix
    groups: opendkim

- name: opendkim defaults
  become: yes
  copy:
    src: opendkim/default
    dest: /etc/default/opendkim
  notify:
    - restart opendkim

- name: opendkim configuration
  become: yes
  copy:
    src: opendkim/opendkim.conf
    dest: /etc/opendkim.conf
  notify:
    - restart opendkim

- name: opendkim key
  become: yes
  copy:
    src: opendkim/simon816.com-dkim.key
    dest: /etc/dkimkeys/simon816.com-dkim.key
    owner: opendkim
    group: opendkim
    mode: 0600
  notify:
    - restart opendkim

- name: Enable postfix service
  become: yes
  service:
    name: postfix
    enabled: yes
    state: started

- name: Enable dovecot service
  become: yes
  service:
    name: dovecot
    enabled: yes
    state: started

- name: Enable opendkim service
  become: yes
  service:
    name: opendkim
    enabled: yes
    state: started

- name: Ensure SSL public cert
  become: yes
  copy:
    src: certs/simon816.com.pem
    dest: /etc/ssl/certs/ssl-cert-simon816.pem
  notify:
    - reload dovecot

- name: Ensure SSL private cert
  become: yes
  copy:
    src: certs/simon816.com.key
    dest: /etc/ssl/private/ssl-cert-simon816.key
  notify:
    - reload dovecot
