network:
  ethernets:
    ens3:
      dhcp4: no
      addresses: [10.80.0.2/24]
      nameservers:
        addresses: [10.80.0.1]
    ens9:
      dhcp4: yes
      routes:
        - to: 192.168.1.100/32
          via: 192.168.122.1
          on-link: true
