network:
  ethernets:
    enp1s0:
      dhcp4: no
      addresses: [10.80.0.2/24]
      nameservers:
        addresses: [10.80.0.1]
    enp2s0:
      dhcp4: yes
      dhcp-identifier: mac
      routes:
        - to: 192.168.0.100/32
          via: 192.168.122.1
          on-link: true
