- name: Route to gateway
  become: yes
  template:
    src: gateway-route.yaml
    dest: /etc/netplan/10-static-cfg.yaml
  notify:
    - apply netplan

- name: Clear bootstrap network
  become: yes
  file:
    state: absent
    path: /etc/netplan/50-cloud-init.yaml
  notify:
    - apply netplan

# Need to apply netplan now for networking to work
- name: Apply network now
  meta: flush_handlers
