- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - msmtp-mta

- name: msmtp config
  become: yes
  template:
    src: config.j2
    dest: /etc/msmtprc

- name: aliases file
  become: yes
  copy:
    content: ""
    dest: /etc/aliases
    force: no

# Might not need this if we allow non-fqdn in submission
- name: root alias
  become: yes
  lineinfile:
    path: /etc/aliases
    line: "root: me@simon816.com"
    regex: "^root:"

# XXX: Temp until DNS forwarding works correctly
- name: mail hostname
  become: yes
  lineinfile:
    path: /etc/hosts
    line: "10.80.0.8 mail.simon816.com"
    search_string: "mail.simon816.com"
