- name: Install packages
  become: yes
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - bsd-mailx

- name: Configure
  become: yes
  copy:
    src: update.conf
    dest: /etc/apt/apt.conf.d/80-custom-auto-updates
