- name: restart youtube-fetcher
  become: yes
  systemd:
    daemon_reload: yes
    name: youtube-fetcher
    state: restarted

- name: restart youtube-metadata-fetcher
  become: yes
  systemd:
    daemon_reload: yes
    name: youtube-metadata-fetcher
    state: restarted
