- name: Install DB packages
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - postgresql
    - python3-psycopg2

- name: Ensure postgres directory
  become: yes
  file:
    path: /srv/postgres
    owner: postgres
    group: postgres
    state: directory

- name: Get postgres data dir
  stat:
    path: /var/lib/postgresql/10/main
  register: postgres_data

- name: Stop postgres if first run
  become: yes
  service:
    name: postgresql
    state: stopped
  when: not postgres_data.stat.islnk

- name: Remove default postgres data
  become: yes
  file:
    path: /var/lib/postgresql/10/main
    state: absent
  when: not postgres_data.stat.islnk

- name: Link postgres data
  become: yes
  file:
    src: /srv/postgres
    dest: /var/lib/postgresql/10/main
    force: yes
    state: link
    owner: postgres
    group: postgres

- name: Setup initial postgres data
  become: yes
  become_user: postgres
  command: /usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main initdb
  when: not postgres_data.stat.islnk

- name: Ensure mariadb started
  become: yes
  service:
    name: mariadb
    state: started

- name: Ensure postgres started
  become: yes
  service:
    name: postgresql
    state: started

- name: Copy postgres configuration
  become: yes
  copy:
    src: pg.conf
    dest: /etc/postgresql/10/main/conf.d/10-dbserver.conf
  notify:
    - restart postgres

- name: Configure postgres permissions
  become: yes
  blockinfile:
    path: /etc/postgresql/10/main/pg_hba.conf
    block: |
        host {{ db.gitlab.name }} {{ db.gitlab.user }} 10.80.0.7/32 md5
        host {{ db.ore.name }} {{ db.ore.user }} 10.80.0.1/32 md5
        host {{ db.pleroma.name }} {{ db.pleroma.user }} 10.80.0.4/32 md5
  notify:
    - restart postgres


